apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: launcher-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: ocs-storagecluster-cephfs
